### ISSUE TITLE
Delete tuple from database after bowtie

### ISSUE THREAD

**Issue by Palledaman** [genomizer/genomizer-server#290] opened 2015-05-20 08:27 UTC
When bowtie has finished running the raw files are deleted from disk, but not from the database. They are still visible as part of the experiment.

**Comment by tastyburger** [comment] 2015-05-20 08:51
Is it the absolute file path that gets stored in the db?

**Comment by tastyburger** [comment] 2015-05-20 09:33
Fixed in ee441e1.

**Comment by tnaeg** [comment] 2015-05-20 10:16
Close the issue if fix is implemented in develop

**Comment by tastyburger** [comment] 2015-05-20 10:53
Should be closed only after it's been verified by the clients that it's working as intended.

**Comment by yakrar** [comment] 2015-06-02 07:38
Status on this?

**Comment by azoimide** [comment] 2015-06-02 10:36
This should be done as of 21094b5

**Closed by azoimide** 2015-06-02 10:36 UTC
Labels: bug, Data Storage
