### ISSUE TITLE
Hide internal structure of server from download URI

### ISSUE THREAD

**Issue by azoimide** [genomizer/genomizer-server#186] opened 2015-04-29 07:16 UTC
The absolute path in the URI could be replaced with the path relative to the file server mount point and concatenated with the entry in the settings file.

Before:

```
/download?path=/Home/staff/niklasf/edu/pvt/genomizer-web/app/data/test_1/profile/0/bearpurse.txt&token=e2b7f71e-594b-41fc-9634-6f79688f08ba
```
After:
```
/download?path=test_1/profile/0/bearpurse.txt&token=e2b7f71e-594b-41fc-9634-6f79688f08ba
```

**Comment by 23Skidoo** [comment] 2015-04-29 07:24
Duplicate of #167.

**Closed by 23Skidoo** 2015-04-29 07:24 UTC
