### ISSUE TITLE
Inconsistent results when uploading new genome releases

### ISSUE THREAD

**Issue by currybullen** [genomizer/genomizer-server#369] opened 2015-05-28 07:47 UTC
Tried adding genome releases both through the web and desktop client with mixed results. The POST command would be received by the server but no response generated. Then it started working suddenly? Not sure whats wrong.

**Comment by tastyburger** [comment] 2015-05-28 11:19
The problem is that the handling of the result set for the genome release queries is overcomplicated and the developer probably made a logical error hence sometimes, the handler never finishes or puts the request in an inconsistent state and so the clients never receives its response.

**Comment by unicornmaster** [comment] 2015-05-28 12:03
Im on it!

**Comment by unicornmaster** [comment] 2015-05-28 12:53
I agree the code is weird, although i'm not sure that this is the issue.

**Comment by tastyburger** [comment] 2015-05-28 12:57
Should nevertheless be revised and tested before moving on with the diagnostic.

**Comment by unicornmaster** [comment] 2015-05-28 13:08
agree

**Comment by unicornmaster** [comment] 2015-05-28 14:11
Currybullen, do you have any idea about the flow? i.e what response are you supposed to get  and where?

**Comment by tastyburger** [comment] 2015-05-29 07:46
What is the status on this? Has the code been refactored yet? Expecting a total fix before the end of the day.

**Comment by unicornmaster** [comment] 2015-05-29 08:03
The refactor is not my higest priority right now. Im not shure what of the code you belive is broken.

**Comment by tastyburger** [comment] 2015-05-29 08:08
It is of the highest priority to fix genome release requests, server is sometimes unresponsive to such requests.

**Comment by unicornmaster** [comment] 2015-05-29 09:12
Here is a refactor, I belive this is better 98205d7f54d22d44e9261b8a2a78a4580c4aedb0

**Comment by timqy** [comment] 2015-06-01 12:08
fixed in #426

**Closed by timqy** 2015-06-01 12:08 UTC
Labels: Data Storage, High priority
